#!/bin/sh

# PROVIDE: warkio
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name='warkio'
rcvar="${name}_enable"

pidfile="/var/run/wark/${name}.pid"
command='/usr/sbin/daemon'

load_rc_config $name

: "${warkio_user:="wark"}"
: "${warkio_chdir:="/usr/home/${warkio_user}/services/${name}"}"
: "${warkio_enable:="NO"}"

command_args="-S -P ${pidfile} -T ${name} ${warkio_chdir}/freebsd/bin/warkio-start"

run_rc_command "$1"
